### ISSUE TITLE
Timer Not working after Kill app

### ISSUE THREAD

**Issue by vishalvanpariya** [dhimant1990/TimerTextView#1]
Usage of This timer is only when we want app open but whenever we kill this app timer all data are clear so that is not useful.

**Comment by dhimant1990** [comment]
Hello Vishal,

This timer is display only remaining time when you setEndTime. So you have to handle your own way according to your requirement by your own.

Thank You,
Dhimant Desai.

**Comment by dhimant1990** [comment]
> Usage of This timer is only when we want app open but whenever we kill this app timer all data are clear so that is not useful.

Hello Vishal,

This timer is display only remaining time when you setEndTime. So you have to handle your own way according to your requirement.

Thank You,
Dhimant Desai.
